#!/bin/bash
#
# Created by: WestleyK
# Email: westley@sylabs.io
# Date: Jul 30, 2018
# version-1.0.4
# https://github.com/WestleyK/easy-clone
#
#
# MIT License
#
# Copyright (c) 2018 WestleyK
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#set -e


source ~/easy-clone/auto-complete.sh

REPO=$1
if [ -z $REPO ]; then
	echo "Usage: hubget [USRNAME/REPO]"
	exit
fi
URL="$( echo "https://github.com/"$REPO )"
git ls-remote $URL
echo $URL
sleep 0.1s
echo "cloning repo"
sleep 0.25s

git clone $URL

IS_FILE=$( cat ~/easy-clone/option-files | grep '$REPO' )
if [[ -z $IS_FILE ]]; then
	echo $REPO >> ~/easy-clone/option-files
fi

echo "Done."


#
# End script
#


